FROM tomcat:8.5.34-jre8

ENV ARTIFACTORY_VERSION 6.5.0
ENV ARTIFACTORY_NAME artifactory-oss-$ARTIFACTORY_VERSION
ENV ARTIFACTORY_FILE jfrog-$ARTIFACTORY_NAME.zip
ENV ARTIFACTORY_URL https://bintray.com/artifact/download/jfrog/artifactory/$ARTIFACTORY_FILE
ENV ARTIFACTORY_HOME /usr/local/artifactory


RUN cd "/tmp" \
 && curl -LO $ARTIFACTORY_URL \
 && unzip $ARTIFACTORY_FILE \
 && mv $ARTIFACTORY_NAME $ARTIFACTORY_HOME

WORKDIR $ARTIFACTORY_HOME
CMD bin/artifactory.sh

VOLUME $ARTIFACTORY_HOME
EXPOSE 8081